dist: xenial

language:
  - php
  - node_js

php:
  - "5.6"
  - "7.0"
  - "7.2"
  - "7.3"

services:
- mysql

addons:
  apt:
    packages:
      - libxml2-utils # For xmllint.

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=trunk WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=1

install:
  - npm install
  - export DEV_LIB_PATH="vendor/xwp/wp-dev-lib/scripts"
  - export DIFF_BASE="master"
  - source "$DEV_LIB_PATH/travis.install.sh"

script:
  - npm run lint-js
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

branches:
  only:
  - master

notifications:
  email: false
